# Generated by Django 2.1.1 on 2018-10-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20181015_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('C', 'Cultural'), ('F', 'Festas'), ('S', 'Shows'), ('E', 'Exposições')], max_length=2, null=True)),
                ('music_taste', models.CharField(blank=True, choices=[('S', 'Sertanejo'), ('F', 'Funk'), ('R', 'Rock'), ('O', 'Outros')], max_length=2, null=True)),
                ('drink', models.CharField(blank=True, choices=[('Y', 'Sim'), ('N', 'Não')], max_length=2, null=True)),
                ('price', models.CharField(blank=True, choices=[('free', 'Sim'), ('10~20', 'De R$10 até R$20'), ('20~30', 'De R$20 até R$30'), ('>30', 'Mais de R$30')], max_length=5, null=True)),
                ('distance', models.CharField(blank=True, choices=[('Y', 'Sim'), ('N', 'Não')], max_length=2, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
