# Generated by Django 2.1 on 2018-10-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181016_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user_rated',
            new_name='user_rater',
        ),
    ]
