# Generated by Django 2.1.1 on 2018-10-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181016_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_animal',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_animal',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
