# Generated by Django 2.1.1 on 2018-10-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181016_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_wishes',
            name='user',
        ),
        migrations.AddField(
            model_name='user_animal',
            name='wishes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User_wishes'),
        ),
    ]
