# Generated by Django 2.1.1 on 2018-10-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20181030_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_wishes',
            new_name='wishes',
        ),
    ]
