# Generated by Django 2.1.1 on 2018-10-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20181030_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='wishes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Wishes'),
        ),
    ]
